In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np
a = [1, 2, 3, 4]

In [2]:
# Create a 1-dimensional NumPy array using np.array()
arr_1d = np.array([1, 2, 3])
print(arr_1d)
print("Shape:", arr_1d.shape)
print("Dimension:", arr_1d.ndim)

[1 2 3]
Shape: (3,)
Dimension: 1


In [3]:
# Create a 2-dimensional NumPy array using np.array()
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)
print("Shape:", arr_2d.shape)
print("Dimension:", arr_2d.ndim)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimension: 2


In [ ]:
# Create a 3-dimensional Numpy array using np.array()
arr_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(arr_3d)
print("Shape:", arr_3d.shape)
print("Dimension:", arr_3d.ndim)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)
Dimension: 3


In [ ]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
print("Shape:", arr_1d.shape)
print("Dimension:", arr_1d.ndim)
print("Data type:", arr_1d.dtype)
print("Size:", arr_1d.size)
print("Type:", type(arr_1d))

Shape: (3,)
Dimension: 1
Data type: int64
Size: 3
Type: <class 'numpy.ndarray'>


In [ ]:
# Attributes of 2-dimensional array
print('Shape:', arr_2d.shape)
print('Dimension:', arr_2d.ndim)
print('Data type:', arr_2d.dtype)
print('Size:', arr_2d.size)
print('Type:', type(arr_2d))

Shape: (2, 3)
Dimension: 2
Data type: int64
Size: 6
Type: <class 'numpy.ndarray'>


In [ ]:
# Attributes of 3-dimensional array
print(arr_3d.shape)
print(arr_3d.ndim)
print(arr_3d.dtype)
print(arr_3d.size)
print(type(arr_3d))

(2, 2, 3)
3
int64
12
<class 'numpy.ndarray'>


In [ ]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(arr_2d, columns=['A', 'B', 'C'])
df

A  B  C
0  1  2  3
1  4  5  6

In [ ]:
# Create an array of shape (10, 2) with only ones
ones_array = np.ones((10, 2))
ones_array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
# Create an array of shape (7, 2, 3) of only zeros
zeros_array = np.zeros((7, 3, 2 ))
zeros_array

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0, 100, 3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [ ]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(0, 10, size=(7, 2))

array([[9, 7],
       [6, 2],
       [3, 9],
       [8, 7],
       [8, 0],
       [9, 2],
       [1, 1]])

In [ ]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_float_array = np.random.rand(3, 5)
random_float_array

array([[0.95231894, 0.18261943, 0.48114231, 0.28287189, 0.67569489],
       [0.68190868, 0.06582527, 0.3534519 , 0.68384371, 0.5709213 ],
       [0.43386735, 0.18011193, 0.94324079, 0.4561851 , 0.02657535]])

In [ ]:
# Set the random seed to 42
np.random.seed(42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array_seeded = np.random.randint(0, 10, size=(4, 6))
random_array_seeded

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [ ]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array2 = np.random.randint(1, 10, size=(3,7))
random_array2
# Find the unique numbers in the array you just created
unique_numbers = np.unique(random_array2)
unique_numbers

array([1, 2, 3, 5, 7, 8, 9])

In [ ]:
# Find the 0'th index of the latest array you created
random_array2[0]

array([2, 5, 8, 9, 9, 1, 9])

In [ ]:
# Get the first 2 rows of latest array you created
random_array2[:2]

array([[2, 5, 8, 9, 9, 1, 9],
       [7, 9, 8, 1, 8, 8, 3]])

In [ ]:
# Get the first 2 values of the first 2 rows of the latest array
random_array2[:2, :2]

array([[2, 5],
       [7, 9]])

In [ ]:
# Create a random array of numbers between 0 & 10 and an array of ones
random_array3 = np.random.randint(0, 10, size=(3, 5))
# both of size (3, 5), save them both to variables
ones_array3 = np.ones((3, 5))
random_array3, ones_array3

(array([[2, 0, 4, 0, 7],
        [0, 0, 1, 1, 5],
        [6, 4, 0, 0, 2]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [ ]:
# Add the two arrays together
sum_array = random_array3 + ones_array3
sum_array

array([[3., 1., 5., 1., 8.],
       [1., 1., 2., 2., 6.],
       [7., 5., 1., 1., 3.]])

In [ ]:
# Create another array of ones of shape (5, 3)
random_array4 = np.random.randint(0, 10, size=(5, 3))
random_array4

array([[5, 0, 8],
       [5, 2, 3],
       [3, 2, 9],
       [2, 2, 3],
       [6, 3, 8]])

In [ ]:
# Try add the array of ones and the other most recent array together
ones_array4 = np.ones((5, 3))

In [ ]:
# Create another array of ones of shape (3, 5)
ones_array5 = np.ones((3, 5))
ones_array5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Subtract the new array of ones from the other most recent array
sub_array = random_array3 - ones_array5
sub_array

array([[ 1., -1.,  3., -1.,  6.],
       [-1., -1.,  0.,  0.,  4.],
       [ 5.,  3., -1., -1.,  1.]])

In [ ]:
# Multiply the ones array with the latest array
mul_array = random_array3 * ones_array3
mul_array

array([[2., 0., 4., 0., 7.],
       [0., 0., 1., 1., 5.],
       [6., 4., 0., 0., 2.]])

In [ ]:
# Take the latest array to the power of 2 using '**'
pow_array = random_array4 ** 2
pow_array

array([[25,  0, 64],
       [25,  4,  9],
       [ 9,  4, 81],
       [ 4,  4,  9],
       [36,  9, 64]])

In [ ]:
# Do the same thing with np.square()
square_array = np.square(random_array4)
square_array

array([[25,  0, 64],
       [25,  4,  9],
       [ 9,  4, 81],
       [ 4,  4,  9],
       [36,  9, 64]])

In [ ]:
# Find the mean of the latest array using np.mean()
mean_array = np.mean(random_array4)
mean_array

np.float64(4.066666666666666)

In [ ]:
# Find the maximum of the latest array using np.max()
max_array = np.max(random_array4)
max_array

np.int64(9)

In [ ]:
# Find the minimum of the latest array using np.min()
min_array = np.min(random_array4)
min_array

np.int64(0)

In [ ]:
# Find the standard deviation of the latest array
std_array = np.std(ones_array)
std_array

np.float64(0.0)

In [ ]:
# Find the variance of the latest array
var_array = np.var(ones_array)
var_array

np.float64(0.0)

In [ ]:
# Reshape the latest array to (3, 5, 1)
reshaped_array = random_array3.reshape(3, 5, 1)
reshaped_array

array([[[2],
        [0],
        [4],
        [0],
        [7]],

       [[0],
        [0],
        [1],
        [1],
        [5]],

       [[6],
        [4],
        [0],
        [0],
        [2]]])

In [ ]:
# Transpose the latest array
transposed_array = random_array2.T
transposed_array

array([[2, 7, 1],
       [5, 9, 8],
       [8, 8, 3],
       [9, 1, 3],
       [9, 8, 1],
       [1, 8, 5],
       [9, 3, 7]])

In [ ]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array_6 = np.random.randint(0, 10, size=(3, 3))
array_7 = np.random.randint(0, 10, size=(3, 2))
array_6, array_7

(array([[0, 7, 6],
        [1, 7, 0],
        [8, 8, 1]]),
 array([[6, 9],
        [2, 6],
        [9, 8]]))

In [ ]:
# Perform a dot product on the two newest arrays you created
dot_product = np.dot(array_6, array_7)
dot_product

array([[ 68,  90],
       [ 20,  51],
       [ 73, 128]])

In [ ]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array_8 = np.random.randint(0, 10, size=(4, 3))
array_9 = np.random.randint(0, 10, size=(4, 3))
array_8, array_9

(array([[3, 0, 1],
        [0, 4, 4],
        [6, 8, 8],
        [2, 2, 2]]),
 array([[3, 7, 5],
        [7, 0, 7],
        [3, 0, 7],
        [3, 5, 7]]))

In [ ]:
# Perform a dot product on the two newest arrays you created
dot_product2 = np.dot(array_8, array_9.T)
dot_product2

array([[ 14,  28,  16,  16],
       [ 48,  28,  28,  48],
       [114,  98,  74, 114],
       [ 30,  28,  20,  30]])

In [ ]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
dot_product3 = np.dot(array_8.T, array_9)
dot_product3

array([[ 33,  31,  71],
       [ 58,  10,  98],
       [ 61,  17, 103]])

In [ ]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
array_10 = np.random.randint(0, 10, size=(3, 3))
array_11 = np.random.randint(0, 10, size=(3, 3))
array_10, array_11

(array([[3, 2, 8],
        [2, 8, 1],
        [1, 1, 5]]),
 array([[2, 8, 3],
        [0, 3, 0],
        [4, 3, 7]]))

In [ ]:
# Compare the two arrays with '>'
array_10 > array_11

array([[ True, False,  True],
       [ True,  True,  True],
       [False, False, False]])

In [ ]:
# Compare the two arrays with '>='
array_10 >= array_11

array([[ True, False,  True],
       [ True,  True,  True],
       [False, False, False]])

In [ ]:
# Find which elements of the first array are greater than 7
array_10 > 7

array([[False, False,  True],
       [False,  True, False],
       [False, False, False]])

In [ ]:
# Which parts of each array are equal? (try using '==')
array_10 == array_11

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [ ]:
# Sort one of the arrays you just created in ascending order
sorted_array = np.sort(array_10)
sorted_array

array([[2, 3, 8],
       [1, 2, 8],
       [1, 1, 5]])

In [ ]:
# Sort the indexes of one of the arrays you just created
sorted_indexes = np.argsort(array_11)
sorted_indexes

array([[0, 2, 1],
       [0, 2, 1],
       [1, 0, 2]])

In [ ]:
# Find the index with the maximum value in one of the arrays you've created
max_index = np.argmax(array_11)
max_index

np.int64(1)

In [ ]:
# Find the index with the minimum value in one of the arrays you've created
min_index = np.argmin(array_11)
min_index

np.int64(3)

In [ ]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
max_indexes = np.argmax(array_11, axis=1)
max_indexes

array([1, 1, 2])

In [ ]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
min_indexes = np.argmin(array_11, axis=0)
min_indexes

array([1, 1, 1])

In [ ]:
# Create an array of normally distributed random numbers
norm_array = np.random.randn(3, 3)
norm_array

array([[ 0.96337613,  0.41278093,  0.82206016],
       [ 1.89679298, -0.24538812, -0.75373616],
       [-0.88951443, -0.81581028, -0.07710171]])

In [ ]:
# Create an array with 10 evenly spaced numbers between 1 and 100
evenly_spaced_array = np.

In [ ]:
b = []
for i in a:
    b.append(i * 2)
b

[2, 4, 6, 8]

In [ ]:
c = np.array([1, 2, 3, 4])
c

array([1, 2, 3, 4])

In [ ]:
c * 2

array([2, 4, 6, 8])

In [ ]:
d = np.array([1, 2, 3])

In [ ]:
d.ndim

1

In [ ]:
d.dtype

dtype('int64')

In [ ]:
d.shape

(3,)

In [ ]:
two_dim = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [ ]:
two_dim.ndim, two_dim.dtype, two_dim.size, two_dim.shape

(2, dtype('int64'), 6, (2, 3))

In [ ]:
three_dim = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],

    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ]
])

In [ ]:
three_dim.ndim, three_dim.dtype, three_dim.size, three_dim.shape

(3, dtype('int64'), 18, (2, 3, 3))

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame(two_dim)

0  1  2
0  1  2  3
1  4  5  6

In [ ]:
three_dim

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [ ]:
two_dim[1]

array([4, 5, 6])

In [ ]:
two_dim[1][1:]

array([5, 6])

In [ ]:
np.ones(shape=(7, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
#(2, 3) * (3, 2) = (2, 2)

In [ ]:
arr1 = np.array([
    [2, 7, 11],
    [10, 35, 41]
])

arr2 = np.array([
    [13, 9, 63, 12],
    [17,11, 28, 45],
    [34, 97, 47, 27]
])

In [ ]:
np.dot(arr1, arr2)

array([[ 519, 1162,  839,  636],
       [2119, 4452, 3537, 2802]])

In [ ]:
np.random.seed(42)
np.random.randint(1, 100, size=(5, 3))

array([[52, 93, 15],
       [72, 61, 21],
       [83, 87, 75],
       [75, 88, 24],
       [ 3, 22, 53]])

In [ ]:
d.max()

3

In [ ]:
#standard deviation -> kokalti sigma
#variance -> sigma^2

In [ ]:
np.sqrt(21704)

147.32277488562318

In [ ]:
arr3 = np.array([
    [13, 17, 96],
    [9, 11, 27],
    [61, 37, 17],
    [87, 4, 38, 2]
])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [ ]:
arr1 * arr3.T

NameError: name 'arr3' is not defined

In [ ]:
g = np.random.randint(1, 1000, size=(7, 3))
g2 = np.random.randint(1, 1000, size=(7, 3))

In [ ]:
g

array([[770, 344, 492],
       [414, 806, 386],
       [192, 956, 277],
       [161, 460, 314],
       [ 22, 253, 748],
       [857, 561, 475],
       [ 59, 511, 682]])

In [ ]:
g2

array([[476, 700, 976],
       [783, 190, 958],
       [687, 958, 563],
       [876, 567, 244],
       [832, 505, 131],
       [485, 819, 647],
       [ 21, 841, 167]])

In [ ]:
sum(g, g2)

array([[2951, 4591, 4350],
       [3258, 4081, 4332],
       [3162, 4849, 3937],
       [3351, 4458, 3618],
       [3307, 4396, 3505],
       [2960, 4710, 4021],
       [2496, 4732, 3541]])

In [ ]:
# Create a 1-dimensional NumPy array using np.array()
import numpy as np
first_arr = np.array([23, 49, 57, 65])
first_arr

array([23, 49, 57, 65])

In [ ]:
# Create a 2-dimensional NumPy array using np.array()
second_arr = np.array([
    [23, 49, 57, 65],
    [38, 55, 78, 27]
])
second_arr

array([[23, 49, 57, 65],
       [38, 55, 78, 27]])

In [ ]:
# Create a 3-dimensional Numpy array using np.array()
third_arr = np.array([
    [[23, 49, 57, 65], [38, 55, 78, 27]],
    [[7, 8, 9, 10], [11, 12, 13, 14]]
])
third_arr

array([[[23, 49, 57, 65],
        [38, 55, 78, 27]],

       [[ 7,  8,  9, 10],
        [11, 12, 13, 14]]])

In [ ]:
first_arr.shape, first_arr.ndim, first_arr.dtype, first_arr.size

((4,), 1, dtype('int64'), 4)

In [ ]:
second_arr.shape, second_arr.ndim, second_arr.dtype, second_arr.size

((2, 4), 2, dtype('int64'), 8)

In [ ]:
third_arr.shape, third_arr.ndim, third_arr.dtype, third_arr.size

((2, 2, 4), 3, dtype('int64'), 16)

In [ ]:
import pandas as pd

df = pd.DataFrame(second_arr, columns=["A", "B", "C", "D"])
df

A   B   C   D
0  23  49  57  65
1  38  55  78  27

In [ ]:
# Array of ones
ones_array = np.ones((10, 2))
ones_array

# Array of zeros
zeros_array = np.zeros((7, 2, 3))
zeros_array

# Array with a range and step
range_array = np.arange(0, 100, 3)
range_array

# Random array of integers
random_int_array = np.random.randint(0, 10, (7, 2))
random_int_array

# Random array of floats
random_float_array = np.random.rand(3, 5)
random_float_array

array([[0.25877998, 0.66252228, 0.31171108, 0.52006802, 0.54671028],
       [0.18485446, 0.96958463, 0.77513282, 0.93949894, 0.89482735],
       [0.59789998, 0.92187424, 0.0884925 , 0.19598286, 0.04522729]])

In [ ]:
np.random.seed(42)
seeded_random_array = np.random.randint(0, 10, (4, 6))
seeded_random_array

# Re-run to confirm reproducibility
np.random.seed(42)
recheck_seeded_random_array = np.random.randint(0, 10, (4, 6))
recheck_seeded_random_array

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [ ]:
random_array = np.random.randint(1, 10, (3, 7))
random_array

# Unique numbers
unique_numbers = np.unique(random_array)
unique_numbers

# 0th index of the array
random_array[0]

# First 2 rows
random_array[:2]

# First 2 values of the first 2 rows
random_array[:2, :2]

array([[9, 1],
       [5, 3]])

In [ ]:
array1 = np.random.randint(0, 10, (3, 5))
array2 = np.ones((3, 5))

# Add two arrays
sum_array = array1 + array2
sum_array

# Another ones array
ones_new = np.ones((5, 3))

# Trying to add them
try:
    error_sum = ones_new + array1
except ValueError as e:
    print("\nError:", e)

# Fixing shape mismatch
# Transpose to fix shape
fixed_sum = array1 + ones_new.T
fixed_sum


Error: operands could not be broadcast together with shapes (5,3) (3,5) 


array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [ ]:
mean_value = np.mean(sum_array)
mean_value

max_value = np.max(sum_array)
max_value

min_value = np.min(sum_array)
min_value

std_deviation = np.std(sum_array)
std_deviation

variance = np.var(sum_array)
variance

# Reshape and transpose
reshaped_array = sum_array.reshape(3, 5, 1)
reshaped_array

transposed_array = sum_array.T
transposed_array

array([[ 7.,  2.,  6.],
       [ 8.,  8., 10.],
       [ 3.,  4.,  4.],
       [ 1.,  2.,  6.],
       [ 4.,  6.,  2.]])

In [ ]:
array_a = np.random.randint(0, 10, (3, 3))
array_b = np.random.randint(0, 10, (3, 3))

# Greater than comparison
array_a > array_b

# Equality
array_a == array_b

# Sorting and finding indexes
sorted_array = np.sort(array_a, axis=1)
sorted_array

index_max = np.argmax(array_a, axis=1)
index_max

index_min = np.argmin(array_b, axis=0)
index_min

array([2, 0, 2])

In [ ]:
massiv = np.array([1,2,3,4,5], dtype= 'int32')
print(massiv)

In [ ]:
massiv.ndim

In [ ]:
second_massiv = np.array([[1, 2, 3], [4, 5, 6]])
print(second_massiv.ndim)

In [ ]:
print(massiv.shape)
print(second_massiv.shape)

In [ ]:
massiv.dtype

In [ ]:
massiv.itemsize

In [ ]:
massiv.nbytes

In [ ]:
second_massiv[1, 1]

In [ ]:
second_massiv[0, :]

In [ ]:
second_massiv[:, 2]

In [ ]:
second_massiv[0, ::2]

In [ ]:
second_massiv[1, 1] = 9
second_massiv

In [ ]:
second_massiv[0, [1, 2]] = [3, 5]
second_massiv

In [ ]:
np.zeros((3, 2))

In [ ]:
np.ones((3, 2), dtype='int16')

In [ ]:
np.full((3,2), 10, dtype= 'int16')

In [ ]:
np.full_like(massiv, 5)

In [ ]:
np.random.rand(5, 2)

In [ ]:
np.random.randint(2,10, size = (5,2))

In [ ]:
np.identity(7)

In [ ]:
alt_massiv = np.array([[3,5,7]])
np.repeat(alt_massiv, 5, axis=0)

In [ ]:
massiv = np.array([1,2,3])
massiv2 = np.array([4,5,6])
massiv2

In [ ]:
massiv +5

In [ ]:
massiv - 3

In [ ]:
massiv * 7

In [ ]:
massiv / 2

In [ ]:
massiv ** 4

In [ ]:
massiv + massiv2

In [ ]:
massiv2 - massiv

In [ ]:
massiv * massiv2

In [ ]:
np.sin(np.pi/2)

In [ ]:
np.cos(np.pi/2)

In [ ]:
import math
math.floor(6.123233995736766e-17)

In [ ]:
matris = np.full((3,4),5)
matris2 = np.full((4,3),4)
new_matris = np.matmul(matris, matris2)

In [ ]:
np.linalg.det(new_matris)

In [ ]:
ikid_matris = np.array(([1,2,3], [4,5,6]))
np.min(ikid_matris, axis=1)
np.max(ikid_matris, axis=1)
np.sum(ikid_matris, axis=1)

In [ ]:
massiv = np.array(([1,2,3,4], [5,6,7,8]))
massiv

In [ ]:
massiv.reshape([4,2])

In [ ]:
massiv1 = np.array(([1,2,3,4,]))
massiv2 = np.array(([5,6,7,8,]))
np.vstack([massiv1, massiv2])

In [ ]:
n1 = np.array([[1, 2], [3, 4]])
n2 = np.array([[5, 6], [7, 8]])

result = np.hstack([n1, n2])

print(result)

In [ ]:
massiv = np.genfromtxt('test.txt', delimiter = ', ')
massiv

In [ ]:
massiv < 40

In [ ]:
a = [5, 11 , 29, 42, 56, 10]

In [ ]:
print(a * 2)

In [ ]:
[i*2 for i in a]

In [ ]:
arr1 = np.array([5, 11 , 29, 42, 56, 10])

In [ ]:
arr1 * 2

In [ ]:
arr1 - 2

In [ ]:
arr1 + 2

In [ ]:
arr1 / 2

In [ ]:
b = np.array([1, 2, 3])

In [ ]:
b.shape

In [ ]:
b.ndim

In [ ]:
c = np.array([[1, 2, 3],
             [4, 5, 6]],
             dtype = float)

In [ ]:
c

In [ ]:
c.shape

In [ ]:
c.size

In [ ]:
c.ndim

In [ ]:
c.dtype

In [ ]:
a = np.array([5])   # scalar
b = np.array([1, 2, 3])   # vector
c = np.array([[1, 2 ,3],
         [4, 5, 6]])  # 2D matrix

In [ ]:
c

In [ ]:
d = np.array([c, c])

In [ ]:
d.ndim

In [ ]:
e = np.array([[[1, 2, 3,],
               [4, 5, 6]],
              [[7, 8, 9],
               [10, 11, 12]]])

In [ ]:
e

In [ ]:
a = np.random.randint(0, 10, size=(2, 5, 3))
a

In [ ]:
np.random.rand(5, 4)    # uniform distribution

In [ ]:
t = np.random.randn(7, 2)   # normal distribution
t

In [ ]:
np.arange(0, 100, 2)  # start | stop | step

In [ ]:
np.random.seed(42)
np.random.randint(0, 10)

In [ ]:
t

In [ ]:
t[5, :]

In [ ]:
t[:2, :]

In [ ]:
A = np.random.randint(0, 100, size=(5, 4))

In [ ]:
A

In [ ]:
A.T

In [ ]:
print(f'A.shape = {A.shape}\nA.T.shape = {A.T.shape}')

In [ ]:
A.reshape(2, 10)

In [ ]:
A.reshape(10, 2)

In [ ]:
Z = np.random.randint(100, 200, size=(1, 1, 1, 5, 4))

In [ ]:
Z.shape

In [ ]:
np.ravel(Z)

In [ ]:
power=np.arange(1, 6)

In [ ]:
power ** 2

In [ ]:
A

In [ ]:
np.mean(A)

In [ ]:
A.mean()

In [ ]:
A.min()

In [ ]:
A.max()

In [ ]:
A.std()

In [ ]:
np.square(A)

In [ ]:
H = np.random.rand(4, )

In [ ]:
H

In [ ]:
H.max()

In [ ]:
H[H.argmax()]     # index

In [ ]:
H[H.argmin()]

In [ ]:
H.min()

In [ ]:
H.argmax()

In [ ]:
H[2]

In [ ]:
mat1 = np.arange(1, 25).reshape(6, 4)

In [ ]:
mat1 * 3

In [ ]:
np.array([1, 2, 3]) * 3

In [ ]:
# (2, 3) * (3, 2) = (2, 2)


# (n, k) * (k, m) = (n, m)

In [ ]:
Mat1

In [ ]:
Mat2

In [ ]:
# np.matmul / np.dot / @

In [ ]:
np.dot(Mat1, Mat2.T)

In [ ]:
np.matmul(Mat1, Mat2.T)

In [ ]:
Mat1 @ Mat2.T

In [ ]:
Mat1 * Mat2

In [ ]:
Mat1.shape

In [ ]:
Mat2.shape

In [ ]:
Mat3 = np.random.randint(10, 100, size=(4, 6))